FROM ghcr.io/mlflow/mlflow:v2.1.1

RUN python -m pip install --upgrade pip
RUN python -m pip install --no-cache-dir psycopg2-binary==2.9.5

WORKDIR /app

ENV LOG_LEVEL=20

EXPOSE 50000

CMD ["/bin/bash"]
