preprocessing:
  additional_features: True
  main_feature_name: "DCOILWTICO"
  main_feature_column_idx: 0
  sequence_length: 16
  use_scaler: False
  train_test_split:
    test_size: 0.3
    random_state: 420

model:
  model_library: "sklearn"
  type: "GradientBoostingRegressor"
  params:
    subsample: 0.5
